name: claim-verification
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - farm-haystack[elasticsearch]==0.11.0  # Specific version of Haystack that includes GenerativeQAPipeline
      - transformers
      - requests
      - beautifulsoup4
      - regex
      - elasticsearch
      - faiss-cpu
      - newsapi-python
