name: claim-verification
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - farm-haystack[elasticsearch]==2.0.0  # Installing Haystack version 2.x
      - transformers
      - requests
      - beautifulsoup4
      - regex
      - elasticsearch
      - faiss-cpu
      - newsapi-python
